name: "CI/CD Pipeline"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - l10n_develop
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'monitoring/grafana-dashboard.json'
      - 'screenshots/**'
    tags-ignore:
      - '*'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'data/static/i18n/*.json'
      - 'frontend/src/assets/i18n/*.json'

env:
  ANGULAR_CLI_VERSION: 13

jobs:
  NodeJS-Build:
    runs-on: self-hosted

    steps:
      - name: Bypass policy for all .ps1 scripts in temp folder
        shell: cmd
        run: |
          for %%F in ("%RUNNER_TEMP%\*.ps1") do (
            powershell.exe -ExecutionPolicy Bypass -File "%%F"
          )

      - name: "Check out Git repository"
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: "Install CLI tools"
        run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION

      - name: "Install application minimalistically"
        run: |
          npm install --ignore-scripts
          cd frontend
          npm install --ignore-scripts --legacy-peer-deps

      - name: "Lint source code"
        run: npm run lint

      - name: "Lint customization configs"
        run: |
          npm run lint:config -- -f ./config/7ms.yml
          npm run lint:config -- -f ./config/addo.yml
          npm run lint:config -- -f ./config/bodgeit.yml
          npm run lint:config -- -f ./config/ctf.yml
          npm run lint:config -- -f ./config/default.yml
          npm run lint:config -- -f ./config/fbctf.yml
          npm run lint:config -- -f ./config/juicebox.yml
          npm run lint:config -- -f ./config/mozilla.yml
          npm run lint:config -- -f ./config/oss.yml
          npm run lint:config -- -f ./config/quiet.yml
          npm run lint:config -- -f ./config/tutorial.yml
          npm run lint:config -- -f ./config/unsafe.yml
